apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q2k1ir5h1-dotnet-basic
  janus-idp.io/tekton: q2k1ir5h1-dotnet-basic
  backstage.io/kubernetes-id: q2k1ir5h1-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q2k1ir5h1-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
